name: cctests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup cctests
        uses: actions/checkout@v3

      - name: Set
        run: npm update --registry=https://registry.npmjs.org/
        
      - name: Run eslint
        run: npm run lint

      - name: Run tests chromium
        env:
          BROWSER: chromium
        run: npm test
      
      - name: Upload test coverage as artifact for ${{ BROWSER }}
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report-${{ BROWSER }}
          path: report
          
      - name: Run tests
        env:
          BROWSER: firefox
        run: npm test
      
      - name: Upload test coverage as artifact for ${{ BROWSER }}
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report-${{ BROWSER }}
          path: report     
