name: cctests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup cctests
        uses: actions/checkout@v3

      - name: Set
        with:
          registry-url: registry http://registry.npmjs.org
      - run: npm ci
      - run: npm publish
      - name: Run tests
        run: npm test
