name: cctests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup cctests
        uses: actions/checkout@v3

      - name: Set
        run: npm update --registry=https://registry.npmjs.org/

      - name: Run tests
        run: npm test
