name: cctests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup cctests
        uses: actions/checkout@v3

      - name: Set
        run: npm update --registry=https://registry.npmjs.org/
        
      - name: Run eslint
        run: npm run lint

      - name: Run tests
        run: npm test
      
      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: report-${{ matrix.os }}
          path: report
